steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aiot-bonvies/sip-js-bonvies', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aiot-bonvies/sip-js-bonvies']

images:
  - 'gcr.io/aiot-bonvies/sip-js-bonvies'

options:
  logging: CLOUD_LOGGING_ONLY