steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/asia-east1-docker.pkg.dev/aiot-bonvies/sip-js-bonvies', '.' ]
images:
- 'gcr.io/asia-east1-docker.pkg.dev/aiot-bonvies/sip-js-bonvies'
options:
  logging: CLOUD_LOGGING_ONLY